### ISSUE TITLE
Missing Xonomy.focus in newAttribute

### ISSUE THREAD

**Issue by fdebef** [michmech/xonomy#29]
In Xonomy.newAttribute is used Xonomy.focus function, that is not defined, if I understand it correctly, line 1247 should look like this:

```if(parameter.value=="") Xonomy.click($(html).prop("id"), "attributeValue"); else focus($(html).prop("id"), "attributeValue");```

**Comment by michmech** [comment]
Ah, that was a typo. The function should be called `Xonomy.setFocus`. Fixed now. Thank you!
