### ISSUE TITLE
jQuery 3.3.x

### ISSUE THREAD

**Issue by fullstackellerbeck** [michmech/xonomy#38]
Hi There,

I'm trying to use xonomy with jQuery 3.3.1 and it doesn't seem to like the $.parseXML function, if I switch to the 1.11.0 version used in the demo on lexiconista it does work. Any ideas on what needs to be changed in able to get this to function with later versions of jQuery?

**Comment by fullstackellerbeck** [comment]
Actually, I see now that is it because of 'use strict' in later versions of jQuery, I can work with this.

**Comment by DigiTransGlasgow** [comment]
Hello, so, is the solution 'just' switching to an old jQuery version? Is there no way of having xonomy to work with the latest jQuery?

**Comment by DigiTransGlasgow** [comment]
PS: if I load 1.11 I get this error:

`ReferenceError: $ is not defined[Learn More] xonomy.js:493:29`
