### ISSUE TITLE
xonomy-click-attribute is not firing

### ISSUE THREAD

**Issue by kiliit** [michmech/xonomy#7]
The xonomy-click-attribute is only fired if Xonomy.attributeMenu(id)="" (line 745).

In my opinion this event should be fired anyway. 

So 

```
var surrogateAttr = Xonomy.harvestAttribute(document.getElementById(htmlID));
$("#"+htmlID).trigger("xonomy-click-attribute", [surrogateAttr]);
```

goes outside the if.

**Comment by michmech** [comment]
You're right, those two lines should be outside the `if` to make sure the event fires every time the user clicks an attribute, regardless of whether the click opens a menu or not. This is fixed now. Thank you.
